### PR TITLE
Feature/maintain table configs

### PR DESCRIPTION
**Pull request by YashNishikant**
The table configurations for courses and professors are now in local storage. Refreshing and changing pages will not reset these configurations to their default values as long as the session has not expired.

### CODE REVIEW

**Comment by DylanPina** [comment]
@YashNishikant Can you please change the target branch to `dev` instead of `main`.

**Comment by YashNishikant** [comment]
Done, thanks

**Comment by DylanPina** [comment]
@YashNishikant Great job, will be moving into main during our upcoming release cycle

**Comment by YashNishikant** [comment]
Thank you, sounds great!

**Pull request merged**
